- block:
    - name: homebrew update
      homebrew:
        update_homebrew: yes

    - name: homebrew packages install
      homebrew:
        name: "{{ item }}"
      with_items: "{{ homebrew_packages }}"

  tags:
    - homebrew
